apiVersion: v1
kind: Service
metadata:
  name: billing-service
  labels:
    app: billing-service
spec:
  selector:
    app: billing-ms
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 3001
#      nodePort: 31110